# Generated by Django 3.2.9 on 2021-11-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenista',
            old_name='trofeos',
            new_name='titulos',
        ),
        migrations.RemoveField(
            model_name='basquetbolista',
            name='altura',
        ),
        migrations.AddField(
            model_name='basquetbolista',
            name='mas_de_dos',
            field=models.BooleanField(default=True),
        ),
    ]
