# Generated by Django 3.2.9 on 2021-11-28 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_auto_20211127_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basquetbolista',
            name='mas_de_dos',
        ),
        migrations.AddField(
            model_name='basquetbolista',
            name='triples',
            field=models.IntegerField(default=0),
        ),
    ]
