# Generated by Django 3.2.9 on 2021-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='avatar',
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
